### ISSUE TITLE
requirements and bush.sh

### ISSUE THREAD

**Issue by lusti-Yu** [ml-postech/Skeleton-anonymization#1]
Hi authors, it's the nice code and a fantastic idea. But I have some problems at runtime, when I install the requirements, there are some links that always report errors. Besides, I can't find the bush.sh file.

**Comment by saemi410** [comment]
Thank you for your attention :)
We fixed requirement.txt and add run.sh
Try again and if you have a problem again, please write a comment.

**Comment by lusti-Yu** [comment]
Thanks for your reply and fix. 
Your fix solved most of bugs, but i still can't install shift-cuda-linear-cpp==0.0.0
Do you know what the reason is?  I would appreciate it :)

**Comment by saemi410** [comment]
Sorry for the late reply. I add the additional file about shift-gcn dependency. 
Please try again :)
